gpring:
  application:
    name: local-grpc-client
grpc:
  client:
    local-grpc-server:
      address: 'static://127.0.0.1:9898'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
server:
  port: 8081
  tomcat:
    threads:
      max: 1